### ISSUE TITLE
Make image fully work with non-root users

### ISSUE THREAD

**Issue by pathob** [aservo/docker-terragrunt#2]
Currently, there is an issue with the Helm provider of Terraform when executing the container with a non-root user.

The Helm provider tries to access the "home directory" (workdir) and write cache files which fails as the home belongs to root.

This can be fixed using a similar approach like done in the Helmfile image.

**Comment by gebae** [comment]
When the container is started with a user/user id <> root and unknown by container-internal /etc/passwd, the $HOME var is not set or set to /. Write operations in $HOME will then normally fail. This can be prevented, if HOME is explicitly set. In Jenkins, we can use "... --env HOME=$WORKSPACE ..." then...

But maybe this situation can also be covered by the image itself (e.g. by using WORKDIR as HOME)?
